enabled: true
uid: 1
allow_uid1: true
allowed_ips: {  }
allowed_origins: {  }
server_name: 'Drupal MCP Tools'
server_version: 1.0.0
server_id: ''
pagination_limit: 50
include_all_tools: true
gateway_mode: false
